config/routes.rb
Rails.application.routes.draw do

  resources :clubs

  resources :users, :only => ['new', 'create']
  resources :clubs, :only => ['new', 'create']
  resources :sessions, :only => ['new', 'create', 'destroy']

  root 'clubs#index'

end

app/models/club.rb
class Club < ActiveRecord::Base
	belongs_to :owner
	has_many :members
	validates :name, presence: true
end

app/models/member.rb
class Member < ActiveRecord::Base
	has_one :user, as: :member
	belongs_to :club
end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_one :user, as: :member
	has_one :club
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	belongs_to :member, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def is_admin
    current_user && current_user.member_type == 'Owner'
  end
  helper_method :is_admin

  def is_admin_logged?
  	redirect_to new_session_path if !is_admin
  end

  def is_logged?
  	redirect_to new_session_path if !current_user
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]
  before_action :is_admin_logged?, only: [:new, :edit, :update, :destroy]
  before_action :is_logged?, only: [:show, :index]

  # GET /clubs
  # GET /clubs.json
  def index
    @club = @current_user.member.club
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    if @current_user.member.club
      redirect_to clubs_path
    else
      @club = Club.new
    end
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)
    @club.owner = @current_user.member

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name, :address)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:member_type] = user.member_type
      redirect_to new_club_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    session[:member_type] = nil
    redirect_to new_session_path, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

  def create
  	@member = params[:user][:member].classify.constantize.create!

  	@user = User.new(user_params)
  	@user.member = @member
  	@user.save!
  	
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clubs/create.html.erb
<h1>Clubs#create</h1>
<p>Find me in app/views/clubs/create.html.erb</p>

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Club</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @club.name %></td>
      <td><%= @club.address %></td>
      <% if is_admin %>
      <td><%= link_to 'Show', @club %></td>
      <td><%= link_to 'Edit', edit_club_path(@club) %></td>
      <% end %>
    </tr>
  </tbody>
</table>

<br>

app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @club.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @club.address %>
</p>

<% if @club.members.present? %>
	<p> Members </p>
	
	<table>
  <% @club.members.each do |member| %>
  <tbody>
    <tr>
      <td><%= member.first_name %></td>
      <td><%= member.last_name %></td>
    </tr>
  </tbody>
  <% end %>
</table>
	
<% end %>

<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pixformance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if session[:user_id] %>
<%= link_to 'logout', session_path(session[:user_id]), method: :delete %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>There was a problem with your registration</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :member %>
    <%= f.select :member, options_for_select([['Owner', Owner], ['Member', Member]]) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Register</h1>
<%= render :partial => "form" %>